### ISSUE TITLE
Create Onboarding Section To README.md

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#14]
1. Thank the contributors.
2. All skill levels are welcomed.
3. Process for how issues are created and assigned.
4. Process for pull requests.
5. Update the boilerplate nextjs guide.
6. Create a table of contents.
7. Add placeholder section for mockups.

**Comment by vasfvitor** [comment]
For 4. A good reference is: https://docs.github.com/en/get-started/quickstart/github-flow
