### ISSUE TITLE
create avatar component

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#20]
### The component should do the following:
* Name it `Avatar.tsx` and place it here: `@/app/components/ui/`
* It should have an `image` prop which will accept an image location as the value.
* It should display a circular avatar with the image centered within it.
* The component and image should fill the `width` of its container.
* The `height` should always match the `width`.
* When you hover over the component, a faint shade of white should overlap the image.

**Usage example:**

```jsx
<Avatar src="https://cdn.discordapp.com/avatars/1234/5678.png)" />
```

**Sample image:**

![avatar](https://github.com/thinkbig-project/thinkbig/assets/3108516/9640b902-1aff-4ff6-8995-4c696eda2c8f)

### Resources
* [React - your first component](https://react.dev/learn/your-first-component)
* [React - passing props to a component](https://react.dev/learn/passing-props-to-a-component)
* [TailwindCSS - Aspect Ratio](https://tailwindcss.com/docs/aspect-ratio)

**Comment by kapoorakshit** [comment]
I can do  #20

**Comment by sujade** [comment]
> I can do #20

Would you still like to handle this? I have time in the coming hours and I can deal with this today (CET).

**Comment by GarlandKey** [comment]
Let's give it to @sujade. In the future, make yourself an Assignee at the top right to claim the issue. I'll have a lot more up later today. Unfortunately, setting up the Discord server took more time than I expected it to. So today I will be finishing the mock-ups and writing issues accordingly.

**Comment by kapoorakshit** [comment]
Ok No problem

**Comment by kapoorakshit** [comment]
can You please follow me
thanks
