### ISSUE TITLE
Create CrudButton component

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#39]
### The component should do the following:

This will be a square button that will display a trash can icon if the type is `delete`, a pencil icon if the type is `update`, or a plus icon if the type is `create`. 

* Name it `CrudButton.tsx` and place it in `@/app/components/ui`
* Type prop: Limited to `create | update | delete`.
* onClick prop: Accepts a function.

**Note:** Do not bring in any new dependencies. We need to create a vector graphic of the following images:
* Trash can
* Plus sign
* Pencil

**Usage example:**

```jsx
<CrudButton
  type='update'
  onClick={handleClick(ticket.id)}
/>
```

**Sample image:**
_Dashboard.tsx_
![dashboard3](https://github.com/thinkbig-project/thinkbig/assets/3108516/5f00e5a5-d254-46e9-ad11-40240ae165f6)

### Resources
* [Inkscape](https://inkscape.org/)
* [React - your first component](https://react.dev/learn/your-first-component)
* [React - passing props to a component](https://react.dev/learn/passing-props-to-a-component)
* [TailwindCSS - Aspect Ratio](https://tailwindcss.com/docs/aspect-ratio)

**Comment by kmooredev** [comment]
Hey, I had some life stuff pop up yesterday, and I'm not going to be able to get to this for a while. If anyone wants to tackle this please assign yourself.

**Comment by vasfvitor** [comment]
sample image isn't showing up. Actually not even on README.md anymore
