### ISSUE TITLE
Create TypeTag component

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#40]
### The component should do the following:

This will be a square image that will display an emoji or icon (not yet decided). It will represent the type of help ticket that is listed on a card. The image displayed will depend on what the value of the `type` prop is. 

* Name it `IssueIcon.tsx` and place it in `@/app/components/ui`
* Type prop: Limited to `assignment | class | code | concept | lfsg | watchAlong`.

**Note:** Do not bring in any new dependencies. We will create all graphics in-house. For now, just use placeholders.

**Note:** Please use `<Image />` for images and not `<img></img>` elements.

**Usage example:**

```jsx
<IssueIcon type='assignment' />
```

**Sample image:**
_Dashboard.tsx_
![dashboard3](https://github.com/thinkbig-project/thinkbig/assets/3108516/5f00e5a5-d254-46e9-ad11-40240ae165f6)

### Resources
* [Inkscape](https://inkscape.org/)
* [React - your first component](https://react.dev/learn/your-first-component)
* [React - passing props to a component](https://react.dev/learn/passing-props-to-a-component)
* [TailwindCSS - Aspect Ratio](https://tailwindcss.com/docs/aspect-ratio)

**Comment by SupaMega24** [comment]
@GarlandKey   Maybe I'm missing something, but how can I see the dashboard on the local host? So far I can only view the homepage, so I can't view if my code is working or not.

**Comment by GarlandKey** [comment]
@SupaMega24 Email me and I'll give you a link to a Google docs file that has our protected variables in it. When you get the link, copy and paste the contents into a new file called `.env.local`.

From there you'll actually be able to log in and see the dashboard.

**Comment by SupaMega24** [comment]
Ok, email sent. Thank you.

**Comment by SupaMega24** [comment]
Alright, I can get to the sign in with discord authorization. However, it says access denied. 

![image](https://github.com/thinkbig-project/thinkbig/assets/138974329/a0ddfbba-1e3b-4401-89c0-a1f0d7c4152d)

![image](https://github.com/thinkbig-project/thinkbig/assets/138974329/e70ca88b-2765-4dda-bb2f-ca24720b384b)

**Comment by SupaMega24** [comment]
Sorry for the confusion on my part.

**Comment by GarlandKey** [comment]
@SupaMega24 Are you behind a VPN or proxy? I had the same issue earlier. Turned off my VPN and it worked immediately.

**Comment by SupaMega24** [comment]
The app is listed as authorized on my discord as well, if that makes any difference.

**Comment by SupaMega24** [comment]
So, here are a few things that I have tried.

1. git fetch and pull to ensure that I'm up to date
2.  disabling VPN on my device
3. removing thinkbig app from my discord authorized apps
4. deleting .next the clear cache and restarting my device
5.  restarting my pc

None of the above have yielded any progress. I did notice that the thinkbig app is now back on my authorized apps on discord, suggesting that it was accepted on that end, but I still get this 



![image](https://github.com/thinkbig-project/thinkbig/assets/138974329/66ec142d-957f-4b18-9673-44f101990535)

**Comment by GarlandKey** [comment]
From what I can tell, this is a cdn issue. Cloudflare is temporarily blocking your IP for making too many requests. Unfortunately, Discord isn't going to share much info on their side.

I am able to duplicate this issue by activating and deactivating my vpn. If it is on, Cloudflare will reject me automatically. Turn it off and I'm authorized.

For now, if you just visit `/dashboard` it will show it. There is no route protection yet.

**Comment by SupaMega24** [comment]
Ok, that seems to work. Thank you. I'm currently using the flavicon as placeholders (hope this is okay) Are there any other instructions for me on this issue?

**Comment by GarlandKey** [comment]
@SupaMega24 Nice! Other than what is already listed, no. I will amend one thing... Call it `IssueIcon.tsx` instead.

**Comment by SupaMega24** [comment]
I think I may be done with this one, according to the description above. Should I wait until the the card component is complete to get a better idea, or just submit the pull request now?

**Comment by GarlandKey** [comment]
You can send in the merge request. Everything we do now will be iterated upon.
