### ISSUE TITLE
Create Tag component

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#41]
### The component should do the following:

This will be a rectangle with slight padding and slightly rounded corners. It will display a unique color and title based on the type prop. We will directly tie a color to each possible type prop. The goal is for them to be compact so that many can be listed together in a small space.

* Name it `Tag.tsx` and place it in `@/app/components/ui`
* Type prop: Limited to `"css" | "ejs" | "html" | "js" | "mongo/mongoose" | "node/express" | "react"`. (Will be expanded later)

**Usage example:**

```jsx
<Tag type='css' />
```

**Sample image:**

![tags](https://github.com/thinkbig-project/thinkbig/assets/3108516/33f91c74-6a4a-42f1-b742-9f212b61cdc4)

### Resources
* [React - your first component](https://react.dev/learn/your-first-component)
* [React - passing props to a component](https://react.dev/learn/passing-props-to-a-component)
* [TailwindCSS - Aspect Ratio](https://tailwindcss.com/docs/aspect-ratio)

**Comment by kysercodes** [comment]
I'm interested in working on this over the weekend, would it be ok to assign this to myself?

**Comment by GarlandKey** [comment]
@kysercodes - Yes. Please assign yourself before someone else assigns it to themselves.

**Comment by JulienMellon** [comment]
Hey I was going to try and snatch this issue up, but I'm not a contributor yet?

**Comment by JulienMellon** [comment]
Should I be working on this in branch "41-create-tag-component" ?

**Comment by kysercodes** [comment]
@JulienMellon i'm open to work on it together if possible but i wont be available for it until tomorrow

**Comment by JulienMellon** [comment]
Hey Antoine shoot me an email or hmu in discord my username is JulienMellon
let’s set up a time that works for you?

Julien Mellon
718.496.1320
***@***.***

**Comment by kysercodes** [comment]
@JulienMellon  my apologies for the late response, I'll catch the next one, gonna be tied up today

**Comment by JulienMellon** [comment]
Hey I think I've got a working commit on the branch; I'm a little lost about how to handle the case of 'what if i get a prop that doesn't match the defined types?'

**Comment by vasfvitor** [comment]
@JulienMellon as I understand you don't need to handle. Set the type to "css" | "ejs" | "html" | "js" | "mongo/mongoose" | "node/express" | "react" and if the type is anything other than those, TypeScript will warn and show the possible types.

example:
```tsx
propName: "css" | "ejs" | "html" | "js" | "mongoose" | "mongo" | "node" | "express" | "react";
```
btw, this is unless the type is to be literally "mongo/mongoose", I'm not sure, if that's the case, just write "mongo/mongoose" together and "node/express" also

**Comment by JulienMellon** [comment]
@vasfvitor I can't figure out where to put the line you wrote for me above...

**Comment by vasfvitor** [comment]
@JulienMellon this is an example of the prop type. You would place in the interface that you set the types, if for instance it was type string, you replace with the example type I mentioned.

To be clear, take a look at my PR (CrudButton) here where there's a interface with type "create" |"delete" | "update" and you'll see more or less what I mean. You may look at other components too

It would be better if I can see your code to point exactly.

**Comment by JulienMellon** [comment]
My commits are in the 41-create-tag-component branch of this repo

I’m going to take a look at your PR now

Julien Mellon

**Comment by JulienMellon** [comment]
hey it worked!  

I'm just not clear on the purpose of :
'''
TagProps extends React.ButtonHTMLAttributes<HTMLButtonElement>{
'''

**Comment by vasfvitor** [comment]
in my case I'm extending the default html button attributes, so my component can accept all the default html button attributes as props. In your case, you don't need it, it's not a button. Just use `interface TagProps {` without the rest
```tsx
interface TagProps {
  tagType: "css" | "ejs" | "html" | "js" | "mongo/mongoose" | "node/express" | "react"
}
```
my bad I was looking in the wrong branch

btw, to show code you use backticks, one for line ` and three for ``` blocks

**Comment by JulienMellon** [comment]
![tagideas](https://github.com/thinkbig-project/thinkbig/assets/101375846/02789d4b-ac38-44d1-ba4d-4a55df20dceb)

not too much info on styling, so here is something that might feel familiar?

**Comment by JulienMellon** [comment]
@vasfvitor thanks so much for your help I think this might be ready for a PR :)

**Comment by GarlandKey** [comment]
@JulienMellon Looks great! I'll take a closer look tomorrow and merge the pr. Sorry for the late response - I got covid during Christmas and have been sleeping a lot to recover. I'm back now.
