### ISSUE TITLE
Protected Routes

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#48]
### Current Behavior

If you haven't logged in and you navigate to `./dashboard`, you will be able to access it.

### Expected Behavior

`./dashboard` is only accessible once you have successfully logged in through Discord.

### Tasks

- [ ] Create a function that verifies that a session exists.
- [ ] Call on that function in `@/app/dashboard/page.tsx` and redirect the user to the home page if a session doesn't exist.

### Files of Interest
- `@/lib/session.ts`
- `@/app/dashboard/page.tsx`
- `@/app/api/auth/[...nextauth]/route.ts`

### Resources
* [next-auth.js.org](https://next-auth.js.org/tutorials/securing-pages-and-api-routes)
* [freecodecamp.org](https://www.freecodecamp.org/news/how-to-setup-authentication-and-protected-route-in-next-js-13-with-next-auth-js) (Skip to, _How to Implement Protected Routes with next-auth.js_)

**Comment by kysercodes** [comment]
Going to take a crack at this over the next couple of days
