### ISSUE TITLE
Create a SideNav Component

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#60]
# Create a SideNav Component

## Description

This is a simple container for navigation components.

## Name & Location

`@/app/components/nav/SideNav.tsx`

* Should have an Avatar component at the bottom as a placeholder.
* Should have a container for buttons that will be added in the future.
* Should be placed in the dashboard component.

## Style

* Should stick to the left side of the viewport.
* Should span the entire height of the viewport.
* Should have a width of `5 rem`
* Should have a padding of `0.5rem`
* Should have a background color of `slate-900`
* Should not scroll.
* Avatar should always be at the bottom of the SideNav.
* Button container should span the full height of the SideNav.
* Everything within the button container should align to the top of the container.

## Sample image

![dashboard3](https://github.com/thinkbig-project/thinkbig/assets/3108516/f204fe0f-f238-4df9-8967-2f3b6edbf5ea)

## Resources

[Tailwindcss.com - Colors](https://tailwindcss.com/docs/customizing-colors)

**Comment by Masch90** [comment]
Hey im interested in working on this :-)

**Comment by GarlandKey** [comment]
@Masch90 I have unassigned myself - feel free! How soon do you think you'll be able to complete it? Asking because it's blocking other issues from being done.

**Comment by Masch90** [comment]
@GarlandKey thank you, I think Tuesday evening.

**Comment by GarlandKey** [comment]
@Masch90 Hey, where are you at on this? If you need an assist, I'm happy to take what you've done and get it ready for a pr. Once it's done, there will be quite a few more issues posted that you might be interested in.
