### ISSUE TITLE
Create a TagMenu

### ISSUE THREAD

**Issue by GarlandKey** [thinkbig-project/thinkbig#67]
## Description

This will be a menu that hovers under a '_Tags_' link when it's clicked. It will add or remove tags from a list row under the '_Tags_' link.

* When hovering over a tag in the menu, it should be highlighted.
* Clicking on a listed tag will add it to the list. Clicking it again will remove it.
* To make the the menu disappear, you only need to click outside of the menu or click the close button at the top right.

## Name & Location

`@/app/components/menus/TagMenu.tsx`

## Style

* Should use the CloseButton component.
* Should use Tag component.
* Should match the style of the sample as closely as possible.

## Sample image

![LabelMenu](https://github.com/thinkbig-project/thinkbig/assets/3108516/e38af45c-5357-4d86-8bd8-47e5165b814e)

**Comment by GarlandKey** [comment]
@SupaMega24 I just changed the name to `@/app/components/menus/TagMenu.tsx`. I forgot to fix that before I posted the issue.

**Comment by SupaMega24** [comment]
@GarlandKey No worries.

**Comment by SupaMega24** [comment]
I'm having issues making way with this one. Thought I could do it but just keep spinning my wheels in the wrong direction. Gonna take myself off of it.

**Comment by GarlandKey** [comment]
@SupaMega24 No worries. Let me know if you want to pair program on it. Otherwise, we'll leave it open. I'm about to add more issues. We're getting to the point where I will need to bounce ideas off of the team.
